### ISSUE TITLE
Not showing all registered chains in https://chains.keplr.app

### ISSUE THREAD

**Issue by zakir-code** [chainapsis/keplr-chain-registry#167]

**Comment by HeesungB** [comment]
@zakir-code Can you tell me more?
When you already registered chain, You can't see that chain in https://chains.keplr.app.

**Comment by zakir-code** [comment]
Yes, many chains are not displayed and can't be searched, but I see in the browser console that all chains are fetched, but only 57 chains are displayed.
![image](https://github.com/chainapsis/keplr-chain-registry/assets/80246097/f02209f7-bcd6-40b9-97b3-cab153a045d5)

The following are not displayed.
![image](https://github.com/chainapsis/keplr-chain-registry/assets/80246097/74f4dee1-43c7-412d-80e9-0647b10a718b)

**Comment by zakir-code** [comment]
![image](https://github.com/chainapsis/keplr-chain-registry/assets/80246097/ddfeb806-d534-4b93-9b9c-87b39288bc1e)

**Comment by zakir-code** [comment]
@HeesungB 
Sorry, I found the reason, if the Keplr plugin has added chain, it will not be displayed here `https://chains.keplr.app/`
