### ISSUE TITLE
Cannot add XPLA to keplr

### ISSUE THREAD

**Issue by vchong** [chainapsis/keplr-chain-registry#295]
Added XPLA via https://chains.keplr.app, but after that, `Search Chains` in https://wallet.keplr.app doesn't show it.
Then, when adding a wallet and Cosmos chains, keplr says that EVM chains can be added at the next step, and in that step it only shows Evmos and Injective, not XPLA.
After that, going to https://wallet.keplr.app/chains/xpla, it says `No token in this wallet.` and `Oops, We can't find this chain.`
Is something wrong? XPLA is already added to this registry: https://github.com/chainapsis/keplr-chain-registry/blob/main/cosmos/dimension_37.json

**Comment by claraexmachina** [comment]
Keplr Dashboard only supports native chains.

**Comment by claraexmachina** [comment]
XPLA is now natively integrated. https://wallet.keplr.app/chains/xpla
