### ISSUE TITLE
Oraichain is a visible chain, however xOCH doesn't show up?

### ISSUE THREAD

**Issue by 4coffeeihadbreakfast** [chainapsis/keplr-chain-registry#364]
How can we add the xOCH token address to Keplr?

**Comment by HeesungB** [comment]
Where can i add Oraichain?

**Comment by 4coffeeihadbreakfast** [comment]
> Where can i add Oraichain?

Keplr -> hamburger menu (top left) -> Manage Chain Visibility -> (search for oraichain) -> click radio box

**Comment by claraexmachina** [comment]
I think he was referring to on which app he can use Oraichain (to get the add chain pop up on their frontend). It seems like the issue is outdated so I will temporarily close this issue, but you can create new issue anytime if it still persists.
