### ISSUE TITLE
Adding a chain already in the registry with a different CoinType

### ISSUE THREAD

**Issue by Rorcual-Nodes** [chainapsis/keplr-chain-registry#383]
I was wondering if it would be possible to add an alternative connection to a chain with a different CoinType knowing there are users with staked funds in the "alternative" one that are not able to access them (after the first upgrade to Keplr v2).

My concern is that it would not be possible to add a .json with the same identifier and having an identifier other than the actual one would result in an error. Am I right?

For instance:

kaiyo.json
kaiyoalt.json

**Comment by toshiSat** [comment]
I know there is an alternativeBIP44s section for keplr, but I'm unsure how to access the alternative cointype in keplr

**Comment by Rorcual-Nodes** [comment]
> I know there is an alternativeBIP44s section for keplr, but I'm unsure how to access the alternative cointype in keplr

Thanks for getting back. I am on the same boat.

**Comment by Thunnini** [comment]
It is correct to use alternativeBIP44s. Please refer to [this](https://github.com/chainapsis/keplr-chain-registry/blob/main/cosmos/mars.json)
