### ISSUE TITLE
Add prysm testnet

### ISSUE THREAD

**Issue by Agajere** [chainapsis/keplr-chain-registry#426]
Please add prysm testnet to chains.kelpr.app
For ease of engagement for its community

**Comment by MarcoLuciano999** [comment]
Please add prysm testnet to chains.kelpr.app
For ease of engagement for its community

**Comment by tonyaaaa11** [comment]
Yup add pryzm_zone please for easy acces

**Comment by DAVIDKARMA** [comment]
Please add prysm testnet to chains.kelpr.app
For ease of engagement for its community

**Comment by ShadowTi** [comment]
Add Prysm Please

**Comment by f0xAction** [comment]
> Add Prysm Please 

Push
