### ISSUE TITLE
Wrong Scorum staking currency

### ISSUE THREAD

**Issue by mglinnik** [chainapsis/keplr-chain-registry#437]
New chain has been added to the list of non-native chains, however, staking currency upon adding it to the keplr is different from what has been requested in schema.
Chain schema:
https://github.com/chainapsis/keplr-chain-registry/blob/main/cosmos/scorum.json

Requested staking currency: SP
Staking currency upon adding via chains.keplr.app: SCR

**Comment by HeesungB** [comment]
@mglinnik Hello. Thank you for reporting the bug.
We've fixed it. Can you check it out?

**Comment by claraexmachina** [comment]
Hi, we are closing this issue as we have not received a response. Please create a new issue if it still persists.
