### ISSUE TITLE
LAVA TESTNET NOT VISIBLE

### ISSUE THREAD

**Issue by taniroy** [chainapsis/keplr-chain-registry#443]
LAVA TESTNET NOT VISIBLE EVEN AFTER WALLET UPPDATE. PLEASE ADD

**Comment by HeesungB** [comment]
@taniroy Hello
Can you give me a little more details about what is happening and what shouldn't be happening?

**Comment by claraexmachina** [comment]
Hi. We will temporarily close this issue due to lack of information about it. Please open a new issue if it still persists. Thank you for your understanding!
