### ISSUE TITLE
Why can't I add a test link to my wallet

### ISSUE THREAD

**Issue by cuier166** [chainapsis/keplr-chain-registry#462]
Why can't I add a test link to my wallet

**Comment by HeesungB** [comment]
@cuier166 Hello
Can you give me a little more details about what is happening and what shouldn't be happening?

**Comment by cuier166** [comment]
> @cuier166 Hello Can you give me a little more details about what is happening and what shouldn't be happening?

I tried to add another test chain to the keplr wallet but couldn't

**Comment by claraexmachina** [comment]
Hi, we are temporarily closing this issue due to lack of information. Please create a new issue if it still persists.
