### ISSUE TITLE
ELYS: Cannot see USDC/Cosmos as Fee

### ISSUE THREAD

**Issue by Wgil** [chainapsis/keplr-chain-registry#482]
After merging https://github.com/chainapsis/keplr-chain-registry/pull/480 and reinstalling Keplr, I cannot see USDC/COSMOS as fee currency. I can however if I add the chain as suggested by the site rather than community driven.

Is there anything we have to do/wait for this to happen?

**Comment by HeesungB** [comment]
@Wgil Hello.
I'd like to test this issue, but I don't have a token.
Can you send me a small amount of tokens to the address below?

`elys1wf87ctwh5pqwugr0x9vemcllyn7vu8q498zfvvà

**Comment by Wgil** [comment]
@HeesungB sorry it's not an issue anymore. I'm closing it, thank you
