### ISSUE TITLE
Lambda stuck in Keplr wallet unable to send

### ISSUE THREAD

**Issue by Mizumist** [chainapsis/keplr-chain-registry#493]
Hello, currently I have Lambda in my Keplr wallet but am unable to do anything with it except delegate it on the Restake app.  I cannot deposit it to Osmosis, nor send it to other wallets.  Below is my public address.  Please advise.  Thank you.

lamb1q2r7ag47a89hj3n5xh3x5g6q3wnxzkxhr9u82e

**Comment by HeesungB** [comment]
@Mizumist Hello. I think you should ask the chain development team.

**Comment by Mizumist** [comment]
Thank you .
Sincerely,

Trevor A. Russell

*“Fear, uncertainty and discomfort are your compa**sses toward growth.”*
